### ISSUE TITLE
Link text stop words - question?

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-a11y-checker#14]
Currently the test is for the existence of a hardcoded string in the array partialAltStopWords which will need to be translated etc.

As this script is now joomla specific why dont we just check for "read more"

I am guessing that we can just check for the value of 
JGLOBAL_READ_MORE="Read more ..."
JGLOBAL_REGISTER_TO_READ_MORE="Register to read more ..."

**Comment by Fedik** [comment]
I think, that for partialAltStopWords and other configurations, we should do as a plugin parameters.

I mean this section should be the plugin options (except langCode):
https://github.com/joomla-projects/joomla-a11y-checker/blob/e6140a41e7c0d1a1abf0f64961212bbe354216ac/src/js/sa11y.js#L38-L157

**Comment by brianteeman** [comment]
upto line 56 I agree

after that I think we can do it better

**Comment by carcam** [comment]
Adding too much configuration will prevent users using the plugin, so I think we should keep it to the bare minimum and provide as much as possible out of the box.

Current default options hardcoded by language will work in most of the situations so adding them as a configuration option will probably be of no use but to make it harder to configure.

Regarding your suggestion @brianteeman I don't think we should remove current stop words and replace them with our beloved "Read more...". When adding content you can use the "download here" to provide a file download and similar. Obviously we should add *JGLOBAL_READ_MORE* so that we can cover this case and any possible language override, but it should not be a replacement for current strings.
