### ISSUE TITLE
Language string line 152: 

### ISSUE THREAD

**Issue by chmst** [joomla-projects/joomla-a11y-checker#26]
Make sure to use semantic lists by using the bullet or number formatting buttons instead.
   
This is  not clear for me: Either it is a unordered list, then it needs bullets or another icon, or it is an ordered list, then it needs numbers.

**Comment by brianteeman** [comment]
You need to look at the test. https://github.com/joomla-projects/joomla-a11y-checker/blob/90c87ad8c93fc000349ddc8e351b35719d187c66/src/js/sa11y.js#L2259

It is looking to see if someone is using paragraphs instead of lists by checking to see if the first character is something you might use for a listing.

It can't tell if the lit should be ul or ol just that it should probably be a list of some type.

**Comment by chmst** [comment]
It was about bullets. 
Not every template uses bullets ( a dot  ) for lists. 
I translate bullet == dot but see that it is a word for every icon of lists.

**Comment by brianteeman** [comment]
in english a "bullet point list" is any list that uses a non alphanumeric indicator
